title: João Otávio Cardoso
logo: /profile-pic-photoaidcom-cropped.jpeg
description: Analista de Dados Jr, com experiência em SQL, Power BI, Excel e Python.
show_downlaods: true
theme: jekyll-theme-minimal
