title: João Otávio Cardoso
logo: /profile-pic-photoaidcom-cropped.jpeg
description: Analista de dados com proficiência em SQL, Power BI, Python, Excel, AWS, entre outras teconologias. Trabalhei na extração de insights a partir de análises avançadas de dados, realizando análises exploratórias, criação e manutenção de dashboards, juntamente de stakeholders. Colaborei com times multifuncionais, incluindo marketing, estoque e logística, fornecendo insights estratégicos para otimizar operações e melhorar a tomada de decisão.
show_downlaods: true
theme: jekyll-theme-minimal
